development:
  id: 2EF52C6C-50A1-4198-ADCF-E73A1871DD34
  target: dukeds-dev
ua_test:
  id: 81785EBC-D2F4-4B28-95FF-DE12CFD9DCE9
  target: dukeds-uatest
production:
  id: C345DCD5-284E-496C-9517-D2F3B0D7E36A
  target: dukeds
