version: '2'
services:
  webapp:
    build: .
    env_file:
      - swift.env
      - webapp.env
      - portal.env
      - neo4j.client.env
    ports:
      - 3001:3000
  db:
    build: ./docker/builds/db
    env_file:
      - db.env
  swiftvol:
    image: busybox
    volumes:
      - /srv
  swift:
    build: ./docker/builds/swift
    ports:
      - 12345:8080
  neo4j:
    image: neo4j:2.3.2
    ports:
      - '7474:7474'
    env_file:
      - neo4j.server.env
