version: '2'
# To make this file default docker-compose file run the following (or add ~/.bash_profile):
# export COMPOSE_FILE=dc-dev.utils.yml
services:
  server:
    extends:
      file: dc-base.yml
      service: webapp
    volumes:
      - .:/var/www/app
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
  db:
    extends:
      file: dc-base.yml
      service: db
  swiftvol:
    extends:
      file: dc-base.yml
      service: swiftvol
  swift:
    extends:
      file: dc-base.yml
      service: swift
    volumes_from:
      - swiftvol
  neo4j:
    extends:
      file: dc-base.yml
      service: neo4j
  swiftcli:
    image: dukedataservice_server
      - server
    entrypoint: ['swift']
  rails:
    image: dukedataservice_server
    volumes_from:
      - server
    entrypoint: ['rails']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
  bundle:
    image: dukedataservice_server
    volumes_from:
      - server
    entrypoint: ['bundle']
  rake:
    image: dukedataservice_server
    volumes_from:
      - server
    entrypoint: ['rake']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
authservice:
  image: dukedataservice_server
  env_file:
    - auth_service.env
    - neo4j.client.env
  volumes_from:
    - server
  entrypoint: ['rake']
  command: authentication_service:create
  links:
    - db:postgres.db.host
    - neo4j:neo4j.db.host
  rspec:
    image: dukedataservice_server
    environment:
      - RAILS_ENV=test
    volumes_from:
      - server
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
    entrypoint: ['rspec']
    command: spec
  deploysecrets:
    image: dukedataservice_server
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - VAULT_ADDR=http://vldfrds02.dhemgt:8200
    volumes_from:
      - server
    volumes:
      - ~/.netrc:/root/.netrc
    command: ['rake', 'heroku_secrets:deploy']
    privileged: true
    tty: true
    network_mode: "host"
  genportal:
    build: ./docker/builds/genportal
    volumes:
      - .:/var/www/app
  genlocalportal:
    build: ./docker/builds/genportal
    environment:
      - USE_LOCAL_PORTAL=1
    volumes:
      - .:/var/www/app
      - ../duke-data-service-portal:/var/www/duke-data-service-portal
  dredd:
    build: ./docker/builds/dredd
    links:
     - server:dds.host
     - swift:swift.circle.host
     - db:postgres.db.host
     - neo4j:neo4j.db.host
    env_file:
      - dredd.env
      - neo4j.client.env
    volumes:
      - ./docker/builds/dredd/dredd_scripts:/home/dredd_scripts/
      - ./apiary.apib:/home/dredd_scripts/apiary.apib
