version: '2'
services:
  server:
    env_file:
      - swift.local.env
      - circle/webapp.circle.env
      - neo4j.client.local.env
      - auth_service.local.env
  rake:
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
  authservice:
    env_file:
      - circle/webapp.circle.env
      - auth_service.local.env
      - neo4j.client.env
