# To add this config to your current environment:
#   export COMPOSE_FILE='docker-compose.yml:docker-compose.override.yml:docker-compose.swift.yml'
#
# Also, update the env symlink:
#   ln -fs swift.local.env swift.env
version: '2'
services:
  swift:
    build: ./docker/builds/swift
    ports:
      - 12345:12345
    volumes:
      - swiftvol:/srv
  server:
    links:
      - swift:swift.local
  rspec:
    links:
      - swift:swift.local
  rails:
    links:
      - swift:swift.local
  worker:
    links:
      - swift:swift.local
  rake:
    links:
      - swift:swift.local
  dredd:
    links:
      - swift:swift.local
volumes:
  swiftvol:
    driver: local
