server:
  extends:
    file: dc-base.yml
    service: webapp
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
db:
  extends:
    file: dc-base.yml
    service: db
swiftvol:
  extends:
    file: dc-base.yml
    service: swiftvol
swift:
  extends:
    file: dc-base.yml
    service: swift
  volumes_from:
    - swiftvol
  ports:
    - 8080:8080
rake:
  image: dukedataservice_server
  entrypoint: ['rake']
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
  env_file:
    - webapp.env
    - swift.env
authservice:
  image: dukedataservice_server
  environment:
    - UUID=342c075a-7aca-4c35-b3f5-29f043884b5b
    - BASE_URI=https://192.168.99.100:3000
    - NAME=Duke Authentication Service
  entrypoint: ['rake']
  command: authentication_service:create
  links:
    - db:postgres.db.host
  env_file:
    - webapp.env
    - swift.env
rspec:
  image: dukedataservice_server
  environment:
    - RAILS_ENV=test
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
  env_file:
    - swift.env
  entrypoint: ['rspec']
  command: spec
