server:
  build: .
  env_file:
    - circle/swift.circle.env
    - circle/webapp.circle.env
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
  ports:
    - 3001:3000
db:
  build: ./docker/builds/db
  env_file:
    - db.env
swiftvol:
  image: busybox
  volumes:
    - /srv
swift:
  build: ./docker/builds/swift
  ports:
    - 8080:8080
rake:
  image: dukedataservice_server
  entrypoint: ['rake']
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
  env_file:
    - circle/webapp.circle.env
    - circle/swift.circle.env
authservice:
  image: dukedataservice_server
  env_file:
    - auth_service.env
  entrypoint: ['rake']
  command: authentication_service:create
  links:
    - db:postgres.db.host
rspec:
  image: dukedataservice_server
  environment:
    - RAILS_ENV=test
  links:
    - db:postgres.db.host
    - swift:swift.circle.host
  env_file:
    - circle/swift.circle.env
  entrypoint: ['rspec']
  command: spec
dredd:
  build: ./docker/builds/dredd
  links:
   - server:dds.host
   - swift:swift.circle.host
   - db:postgres.db.host
  env_file:
    - dredd.env
  volumes:
    - ./docker/builds/dredd/dredd_scripts:/home/dredd_scripts/
    - ./apiary.apib:/home/dredd_scripts/apiary.apib
#Sometimes need to run interactively to qc issues, so here is the docker invocation
# docker run \
# -it \
# -v /home/ubuntu/duke-data-service/docker/builds/dredd/dredd_scripts:/home/dredd_scripts/ \
# -v /home/ubuntu/duke-data-service/apiary.apib:/home/dredd_scripts/apiary.apib \
# --link server:dds.host \
# --link swift:swift.circle.host \
# --link db:postgres.db.host \
# --env HOST_NAME=http://dds.host:3000/api/v1 \
# --env MY_GENERATED_JWT=`docker-compose run rake api_test_user:create | tail -1` \
# dukedataservice_dredd bash
