version: '2'
services:
  server:
    build: .
    ports:
      - 3001:3000
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - swift.local.env
      - circle/webapp.circle.env
      - neo4j.client.local.env
      - auth_service.local.env
      - elastic.client.local.env
  db:
    build: ./docker/builds/db
    env_file:
      - db.env
  neo4j:
    image: neo4j:3.1.6
    ports:
      - '7474:7474'
    env_file:
      - neo4j.server.env
  elasticsearch:
    image: elasticsearch:5.4.3
    ports:
      - '9200:9200'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: elasticsearch -E 'action.auto_create_index=false'
  worker:
    image: dukedataservice_server
    entrypoint: ['rake', 'workers:run']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
      - elastic.client.local.env
  rails:
    image: dukedataservice_server
    entrypoint: ['rails']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
      - elastic.client.local.env
  rake:
    image: dukedataservice_server
    entrypoint: ['rake']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
      - elastic.client.local.env
  authservice:
    image: dukedataservice_server
    entrypoint: ['rake']
    command: authentication_service:create
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - circle/webapp.circle.env
      - auth_service.local.env
      - neo4j.client.local.env
      - elastic.client.local.env
  rspec:
    image: dukedataservice_server
    environment:
      - RAILS_ENV=test
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - elasticsearch:elastic.local
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
      - elastic.client.local.env
    entrypoint: ['rspec']
    command: spec
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.5-management
    ports:
      - "12345:5672"
  dredd:
    build: ./docker/builds/dredd
    links:
     - server:dds.host
    volumes:
      - ./docker/builds/dredd/dredd_scripts:/home/dredd_scripts/
      - ./apiary.apib:/home/dredd_scripts/apiary.apib
