version: '2'
services:
  server:
    env_file:
      - swift.local.env
      - circle/webapp.circle.env
      - neo4j.client.local.env
      - auth_service.local.env
  rails:
    image: dukedataservice_server
    entrypoint: ['rails']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - webapp.env
      - swift.env
      - neo4j.client.env
  rake:
    image: dukedataservice_server
    entrypoint: ['rake']
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - circle/webapp.circle.env
      - swift.local.env
      - neo4j.client.local.env
  authservice:
    image: dukedataservice_server
    entrypoint: ['rake']
    command: authentication_service:create
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - circle/webapp.circle.env
      - auth_service.local.env
      - neo4j.client.env
  rspec:
    image: dukedataservice_server
    environment:
      - RAILS_ENV=test
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
    env_file:
      - circle/webapp.circle.env
      - swift.env
      - neo4j.client.local.env
    entrypoint: ['rspec']
    command: spec
  dredd:
    build: ./docker/builds/dredd
    links:
     - server:dds.host
    volumes:
      - ./docker/builds/dredd/dredd_scripts:/home/dredd_scripts/
      - ./apiary.apib:/home/dredd_scripts/apiary.apib
