version: '2'
services:
  swift:
    build: ./docker/builds/swift
    ports:
      - 12345:12345
    volumes:
      - swiftvol:/srv
  server:
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - swift:swift.local
  rspec:
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - swift:swift.local
  rails:
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - swift:swift.local
  rake:
    links:
      - db:postgres.db.host
      - neo4j:neo4j.db.host
      - swift:swift.local
  dredd:
    links:
      - server:dds.host
      - swift:swift.local
volumes:
  swiftvol:
    driver: local
