import dredd_hooks as hooks
import imp
import os
import json
import uuid
#if you want to import another module for use in this workflow
utils = imp.load_source("utils",os.path.join(os.getcwd(),'utils.py'))

###############################################################################
###############################################################################
#           SYSTEM PERMISSIONS
###############################################################################
###############################################################################
@hooks.before("System Permissions > System Permissions collection > List system permissions")
@hooks.before("System Permissions > System Permission instance > Grant system permission")
@hooks.before("System Permissions > System Permission instance > View system permission")
@hooks.before("System Permissions > System Permission instance > Revoke system permission")
#Note: the DDS user generated by rake doesn't have permission for these 4 endpoints, need to request access if important
def skippy(transaction):
    utils.skip_this_endpoint(transaction)
