import dredd_hooks as hooks
import imp
import os
import json
import uuid


###############################################################################
###############################################################################
#           SYSTEM PERMISSIONS
###############################################################################
###############################################################################
@hooks.before("System Permissions > System Permissions collection > List system permissions")
@hooks.before("System Permissions > System Permission instance > Grant system permission")
@hooks.before("System Permissions > System Permission instance > View system permission")
@hooks.before("System Permissions > System Permission instance > Revoke system permission")
#Note: the DDS user generated by rake doesn't have permission for these 4 endpoints, need to request access if important
def skippy(transaction):
    transaction['skip'] = True
