FORMAT: 1A
HOST: https://apidev.dataservice.duke.edu/api/v1

# Duke Data Service

The Duke Data Service (DDS) API allows Duke researchers to store, organize, retrieve, share and generate provenance for data.

This the documentation for the Data Service API. Key focuses are on API endpoints that enhance usability for "shallow end of the pool" users, endpoints that support the needs of investigators for managing their research groups, endpoints that accommodate shared resource and core facility needs, endpoints that support SOM administration of data resources, and endpoints that facilitate reproducible scientific workflows. There are tensions to resolve to meet these needs, and we should consider whether the API might be broken up into multiple APIs, whether some business logic be pushed to the users, etc.

Adhere as well as possible to the [Heroku API Design Best Practices:](https://geemus.gitbooks.io/http-api-design/content/en/index.html) requiring secure TLS connections, versioning in the accepts header, supporting Etags, including a Request-id in each response header, among others.

### **[API Basics](api_basics.html)**
+ Contains general usage details (i.e. authentication, standard errors, pagination, etc.) and change log.

### **[Users and Software Agents](users_software_agents.html)**
+ Contains endpoints for Current User, Users, Software Agents, Authentication Providers

### **[Authorization](authorization.html)**
+ Contains endpoints for Authorization Roles, System Permissions

### **[Projects](projects.html)**
+ Contains endpoints for Projects, Project Collaboration (i.e. currently Project Permissions), Project Roles, Project Affiliates

### **[Folders and Files](folders_files.html)**
+ Contains endpoints for Folders, Uploads, Files, File Versions, Browse Project/Folder Tree (i.e. currently Search Children), Storage Providers

### **[Provenance](provenance.html)**
+ Contains endpoints Provenance Activities, Provenance Relations, Search Provenance Graph

### **[Metadata](metadata.html)**
+ Contains endpoints for Tags and advanced Metadata (Key/Value Pairs)

### **[Search](search.html)**
+ Contains endpoint for Search Objects

### **[Core Facility Workflow](core_facility_workflow.html)**
+ Contains endpoints for Project Transfer
