FORMAT: 1A

## Provenance
[Home](index.html)

## Group Provenance Activities
Represents the main record of provenance in DDS; it is analogous to *Activity* defined in the [W3C Specification on Provenance](https://www.w3.org/TR/prov-primer/).  Activities are recorded/tracked by researchers and their *Software Agents* with the intent of maintaining comprehensive data provenance.

*Note: Provenance relations to an activity, such as* `used` *and* `wasGeneratedBy` *are managed through the* **Provenance Relations** *API actions.*

## Activities collection [/activities]

### Create activity [POST]
>**Permission:** authenticated
- - - - -

>**Properties**
- - - - -
+ **name (string, required)** - A short name for this activity.
+ **description (string, optional)** - A verbose description for this activity.
+ **started_on (string, optional)** - The time this activity was started; defaults to the current datetime if not specified.
+ **ended_on (string, optional)** - The time this activity ended.

>**Rules**
- - - - -
+ The `ended_on` time must be greater than or equal to the `started_on` time.

**Response messages:**
* 200: This will never happen
* 201: Successfully Created
* 400: Activity requires a name
* 401: Unauthorized
* 403: Forbidden

+ Request (application/json)

        {
            "name": "RF PI3-Kinase",
            "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity"
        }

+ Response 201 (application/json)

        {
            "kind": "dds-activity",
            "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
            "name": "RF PI3-Kinase",
            "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
            "started_on": "2015-01-01T12:00:00Z",
            "ended_on": null,
            "is_deleted": false,
            "audit": { }
        }

### List activities [GET]
>**Permission:**
- - - - -
+ authenticated [scope: creator *or* visiblity to single entity that has a provenance relation to the activity]

>**Rules**
- - - - -
+ Activities that have been deleted (i.e. `"is_deleted": true`) are not included.

**Response messages:**
* 200: Success
* 401: Unauthorized
* 403: Forbidden

+ Response 200 (application/json)

        {
            "results": [
                {
                    "kind": "dds-activity",
                    "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                    "name": "RF PI3-Kinase",
                    "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                    "started_on": "2015-01-01T12:00:00Z",
                    "ended_on": null,
                    "is_deleted": false,
                    "audit": { }
                }
            ]
        }

## Activities instance [/activities/{id}]
+ Parameters
    + id (string, required, `a1ff02a4-b7e9-999d-87x1-66f4c881jka1`) ... The unique id of the activity.

### View activity [GET]
>**Permission:**
- - - - -
+ creator *or* visiblity to single entity that has a provenance relation to the activity

**Response messages:**
* 200: Success
* 401: Unauthorized
* 403: Forbidden
* 404: Activity does not exist

+ Response 200 (application/json)

        {
            "kind": "dds-activity",
            "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
            "name": "RF PI3-Kinase",
            "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
            "started_on": "2015-01-01T12:00:00Z",
            "ended_on": null,
            "is_deleted": false,
            "audit": { }
        }

### Update activity [PUT]
>**Permission:** creator
- - - - -

>**Rules**
- - - - -
+ Only `name`, `description`, `started_on`, and `ended_on` properties may be updated via this action.

**Response messages:**
* 200: Success
* 400: Validation Error
* 401: Unauthorized
* 403: Forbidden (activity restricted)
* 404: Activity does not exist

+ Request (application/json)

        {
            "ended_on": "2015-01-01T14:30:00Z"
        }

+ Response 200 (application/json)

        {
            "kind": "dds-activity",
            "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
            "name": "RF PI3-Kinase",
            "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
            "started_on": "2015-01-01T12:00:00Z",
            "ended_on": "2015-01-01T14:30:00Z",
            "is_deleted": false,
            "audit": { }
        }

### Delete activity [DELETE]
>**Permission:** creator
- - - - -

**Response messages:**
* 204: Successfully Deleted
* 401: Unauthorized
* 403: Forbidden (activity restricted)
* 404: Activity does not exist

+ Response 204

## Group Provenance Relations
Represents provenance relations as defined in the [W3C Specification on Provenance](https://www.w3.org/TR/prov-primer/).  Relations are recorded/tracked by researchers and their *Software Agents* with the intent of maintaining comprehensive data provenance.

## Relations collection [/relations]

### Create used relation [POST /relations/used]
>**Permission:** creator of the activity *and* visibility to the `used` entity
- - - - -

>**Properties**
- - - - -
+ **activity.id (string, required)** - The activity that used the entity.
+ **entity.kind (string, required)** - The kind of entity that was used; this must be a file version (i.e. `dds-file-version`).
+ **entity.id (string, required)** - The unique id of the used entity.

>**Rules**
- - - - -
+ An entity (i.e. `file_version`) cannot be used and generated by the same activity (i.e. `dds-activity`).

**Response messages:**
* 200: This will never happen
* 201: Successfully Created
* 400: Activity and Entity are required, Activity generated Entity
* 401: Unauthorized
* 403: Forbidden

+ Request (application/json)

        {
            "activity": {
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1"
            },
            "entity": {
                "kind": "dds-file-version",
                "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b"
            }
        }

+ Response 201 (application/json)

        {
            "kind": "dds-relation-used",
            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
            "from": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                "name": "RF PI3-Kinase",
                "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                "started_on": "2015-01-01T12:00:00Z",
                "ended_on": "2015-01-01T14:30:00Z",
                "is_deleted": false,
                "audit": { }
            },
            "to": {
                "kind": "dds-file-version",
                "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 1,
                "label": "Post pairwise sequence alignment (piecewise)",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "audit": { }
        }

### Create was generated by relation [POST /relations/was_generated_by]
>**Permission:** creator of the activity *and* update_file for the `wasGeneratedBy` entity
- - - - -

>**Properties**
- - - - -
+ **entity.kind (string, required)** - The kind of entity that was generated; this must be a file version (i.e. `dds-file-version`).
+ **entity.id (string, required)** - The unique id of the generated entity.
+ **activity.id (string, required)** - The activity that generated the entity.

>**Rules**
- - - - -
+ An entity (i.e. `file_version`) can be generated by one and only one activity (i.e. `dds-activity`).
+ An entity (i.e. `file_version`) cannot be used and generated by the same activity (i.e. `dds-activity`).

**Response messages:**
* 200: This will never happen
* 201: Successfully Created
* 400: Activity and Entity are required, Entity can only be generated by one Activity, cannot be used by the same Activity
* 401: Unauthorized
* 403: Forbidden

+ Request (application/json)

        {
            "entity": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3"
            },
            "activity": {
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1"
            }
        }

+ Response 201 (application/json)

        {
            "kind": "dds-relation-was-generated-by",
            "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
            "from": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 2,
                "label": "Alignment performed on raw data",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "to": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                "name": "RF PI3-Kinase",
                "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                "started_on": "2015-01-01T12:00:00Z",
                "ended_on": "2015-01-01T14:30:00Z",
                "is_deleted": false,
                "audit": { }
            },
            "audit": { }
        }

### Create was derived from relation [POST /relations/was_derived_from]
>**Permission:** visibility to the `used` entity and update_file for the `generated` entity.
- - - - -

>**Properties**
- - - - -
+ **generated_entity.kind (string, required)** - The kind of entity generated by the derivation; this must be a file version (i.e. `dds-file-version`).
+ **generated_entity.id (string, required)** - The unique id of the generated entity.
+ **used_entity.kind (string, required)** - The kind of entity used by the derivation; this must be a file version (i.e. `dds-file-version`).
+ **used_entity.id (string, required)** - The unique id of the used entity.

**Response messages:**
* 200: This will never happen
* 201: Successfully Created
* 400: Activity and Entity are required
* 401: Unauthorized
* 403: Forbidden

+ Request (application/json)

        {
            "generated_entity": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3"
            },
            "used_entity": {
                "kind": "dds-file-version",
                "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b"
            }
        }

+ Response 201 (application/json)

        {
            "kind": "dds-relation-was-derived-from",
            "id": "6bf31123-b078-4655-ae4e-be599d52adc5",
            "from": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 2,
                "label": "Alignment performed on raw data",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "to": {
                "kind": "dds-file-version",
                "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 1,
                "label": "Initial raw data from device",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "audit": { }
        }

### Create was invalidated by relation [POST /relations/was_invalidated_by]
>**Permission:** creator of the activity *and* delete_file for `wasInvalidatedBy` entity
- - - - -

>**Properties**
- - - - -
+ **entity.kind (string, required)** - The kind of entity that was invalidated; this must be a file version (i.e. `dds-file-version`).
+ **entity.id (string, required)** - The unique id of the invalidated entity.
+ **activity.id (string, required)** - The activity that invalidated the entity.

>**Rules**
- - - - -
+ The `invalidated` entity must be in a deleted state (i.e. `"is_deleted": true`).
+ An entity (i.e. `file_version`) can be invalidated by one and only one activity (i.e. `dds-activity`).

**Response messages:**
* 200: This will never happen
* 201: Successfully Created
* 400: Activity and Entity are required
* 401: Unauthorized
* 403: Forbidden

+ Request (application/json)

        {
            "entity": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3"
            },
            "activity": {
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1"
            }
        }

+ Response 201 (application/json)

        {
            "kind": "dds-relation-was-generated-by",
            "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
            "from": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 2,
                "label": "Alignment performed on raw data",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "to": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                "name": "RF PI3-Kinase",
                "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                "started_on": "2015-01-01T12:00:00Z",
                "ended_on": "2015-01-01T14:30:00Z",
                "is_deleted": false,
                "audit": { }
            },
            "audit": { }
        }

### List provenance relations [GET /relations/{object_kind}/{object_id}]
List the relations for a provenance node; this only lists direct relations for the node that are a single hop away.
>**Permission:** visibility to the specified (starting) provenance node (i.e. `object_kind`, `object_id`) - which may be an activity *or* an entity
- - - - -

>**Rules**
- - - - -
+ Provenance relations that have been deleted (i.e. `"is_deleted": true`) are not included.

**Response messages:**
* 200: Success
* 401: Unauthorized
* 403: Forbidden
* 404: Object kind or id does not exist

+ Parameters
    + object_kind (string, required, `dds-activity`) ... The kind of provenance node; can be one of dds-activity or dds-file-version.
    + object_id (string, required, `a1ff02a4-b7e9-999d-87x1-66f4c881jka1`) ... The unique id of the node.

+ Response 200 (application/json)

        {
            "results": [
                {
                    "kind": "dds-relation-used",
                    "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
                    "from": {
                        "kind": "dds-activity",
                        "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "name": "RF PI3-Kinase",
                        "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                        "started_on": "2015-01-01T12:00:00Z",
                        "ended_on": "2015-01-01T14:30:00Z",
                        "is_deleted": false,
                        "audit": { }
                    },
                    "to": {
                        "kind": "dds-file-version",
                        "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                        "file": {
                            "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                            "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                            "project": {
                                "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                            }
                        },
                        "version": 1,
                        "label": "Post pairwise sequence alignment (piecewise)",
                        "is_deleted": false,
                        "upload": {
                            "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                            "size": 30024000,
                            "hashes": [
                                {
                                    "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                                    "algorithm": "md5",
                                    "audit": { }
                                }
                            ],
                            "storage_provider": {
                                "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                                "name": "duke_oit_swift",
                                "description": "Duke OIT Storage"
                            }
                        },
                        "audit": { }
                    },
                    "audit": { }
                }
            ]
        }

## Relation instance [/relations/{id}]
+ Parameters
    + id (string, required, `ac242faf-fba0-4293-a949-0b82ae7ba810`) ... The unique id of the provenance relation.

### View relation [GET]
>**Permission:** visibility to a single node for the specified relation - which may be the activity *or* the entity

**Response messages:**
* 200: Success
* 401: Missing, Expired, or Invalid API Token in 'Authorization' Header
* 403: Forbidden
* 404: Relation does not exist

+ Response 200 (application/json)

        {
            "kind": "dds-relation-used",
            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
            "from": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                "is_deleted": false,
                "audit": { }
            },
            "to": {
                "kind": "dds-file-version",
                "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 1,
                "label": "Post pairwise sequence alignment (piecewise)",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "audit": { }
        }

+ Response 200 (application/json)

        {
            "kind": "dds-relation-was-associated-with",
            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
            "from": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                "name": "RF PI3-Kinase",
                "description": "Building a Random Forest as a heuristic for PI3-Kinase pathway activity",
                "started_on": "2015-01-01T12:00:00Z",
                "ended_on": "2015-01-01T14:30:00Z",
                "is_deleted": false,
                "audit": { }
            },
            "to": {
                "kind": "dds-user",
                "id": "c1179f73-0558-4f96-afc7-9d251e65b7bb",
                "username": "mrgardner01",
                "first_name": "Matthew",
                "last_name": "Gardner",
                "full_name": "Matthew Gardner",
                "email": "mrgardner01@duke.edu",
                "auth_provider": {
                    "source": "duke_shibboleth",
                    "uid": "gardner100"
                },
                "last_login_on": "2015-01-01T12:00:00Z",
                "audit": { }
            },
            "audit": { }
        }

+ Response 200 (application/json)

        {
            "kind": "dds-relation-was-attributed-to",
            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
            "from": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 2,
                "label": "Alignment performed on raw data",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "to": {
                "kind": "dds-user",
                "id": "c1179f73-0558-4f96-afc7-9d251e65b7bb",
                "username": "mrgardner01",
                "first_name": "Matthew",
                "last_name": "Gardner",
                "full_name": "Matthew Gardner",
                "email": "mrgardner01@duke.edu",
                "auth_provider": {
                    "source": "duke_shibboleth",
                    "uid": "gardner100"
                },
                "last_login_on": "2015-01-01T12:00:00Z",
                "audit": { }
            },
            "audit": { }
        }

+ Response 200 (application/json)

        {
            "kind": "dds-relation-was-attributed-to",
            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
            "from": {
                "kind": "dds-file-version",
                "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                "file": {
                    "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                    "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata",
                    "project": {
                        "id": "ca29f7df-33ca-46dd-a015-92c46fdb6fd1"
                    }
                },
                "version": 2,
                "label": "Alignment performed on raw data",
                "is_deleted": false,
                "upload": {
                    "id": "666be35a-98e0-4c2e-9a17-7bc009f9bb23",
                    "size": 30024000,
                    "hashes": [
                        {
                            "value": "cf23df2207d99a74fbe169e3eba035e633b65d94",
                            "algorithm": "md5",
                            "audit": { }
                        }
                    ],
                    "storage_provider": {
                        "id": "g5579f73-0558-4f96-afc7-9d251e65bv33",
                        "name": "duke_oit_swift",
                        "description": "Duke OIT Storage"
                    }
                },
                "audit": { }
            },
            "to": {
                "kind": "dds-software-agent",
                "id": "9a4c28a2-ec18-40ed-b75c-3bf5b309715f",
                "name": "Sample pipeline agent",
                "description": null,
                "repo_url": null,
                "is_deleted": false,
                "audit": { }
            },
            "audit": { }
        }

### Delete relation [DELETE]
>**Permission:** creator

**Response messages:**
* 204: Successfully Deleted
* 401: Unauthorized
* 403: Forbidden
* 404: Relation does not exist

+ Response 204

## Group Search Provenance
The `Provenance Relations` API actions allows users and software agents to record the use and production of entities (i.e. files, file versions, etc.) by research activities, which may be influenced in various ways by agents.  The resulting provenace chain is organized as a [graph structure](https://en.wikipedia.org/wiki/Graph_database).  The search API can be used by client applications to extract the provenace graph in a JSON data format that can be transformed to a visual representation.

*Note: The provenance graph structure is stored in a* [Neo4J](http://neo4j.com) *database and ubiquitous JavaScript libraries can be used for* [graph rendering](http://neo4j.com/developer/guide-data-visualization).

## Search Provenance [POST /search/provenance]
Given a starting node, returns a graph structure for the provenance chain.  This structure is based on the Neo4J JSON graph format.
>**Permission:** visibility to the specified (starting) provenance node (i.e. `start_node.kind`, `start_node.id`) - which may be an activity *or* an entity
- - - - -

>**Rules:**
- - - - -
+ If the user does not have visibilty to a `node` in the resulting graph, the `properties` attribute for that `node` will be a partial resource containing: `kind`, `id`, and `is_deleted`.

>**Properties**
- - - - -
+ **start_node.kind (string, required)** - The kind of provenance node; can be one of `dds-activity` or `dds-file-version`.
+ **start_node.id (string, required)** - The unique id of the node.
+ **max_hops (number, optional)** -  The max number of hops (degree of node separation) to traverse from the starting node; defaults to infinity.

**Response messages:**
* 200: This will never happen
* 201: Success
* 401: Unauthorized
* 404: start_node or start_node kind does not exist

+ Request (application/json)

        {
            "start_node": {
                "kind": "dds-activity",
                "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1"
            }
        }

+ Response 201 (application/json)

        {
            "graph": {
                "nodes": [
                    {
                        "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "labels": ["Activity"],
                        "properties": {
                            "kind": "dds-activity",
                            "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                            "name": "RF PI3-Kinase",
                            "is_deleted": false,
                            "audit": { }
                        }
                    },
                    {
                        "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                        "labels": ["File Version"],
                        "properties": {
                            "kind": "dds-file-version",
                            "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                            "file": {
                                "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                                "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata"
                            },
                            "version": 1,
                            "label": "Initial raw data from device",
                            "is_deleted": false,
                            "audit": { }
                        }
                    },
                    {
                        "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                        "labels": ["File Version"],
                        "properties": {
                            "kind": "dds-file-version",
                            "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                            "file": {
                                "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                                "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata"
                            },
                            "version": 2,
                            "label": "Alignment performed on raw data",
                            "is_deleted": false,
                            "audit": { }
                        }
                    }
                ],
                "relationships": [
                    {
                        "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
                        "type": "used",
                        "start_node": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "end_node": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                        "properties": {
                            "kind": "dds-relation-used",
                            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
                            "audit": { }
                        }
                    },
                    {
                        "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
                        "type": "wasGeneratedBy",
                        "start_node": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                        "end_node": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "properties": {
                            "kind": "dds-relation-was-generated-by",
                            "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
                            "audit": { }
                        }
                    }
                ]
            }
        }

## Search Provenance Origin [POST /search/provenance/origin]
This is a targeted query that navigates "up" the provenance chain for a file version to see how it was generated (i.e. by what activity) and from what source file versions.  Given a list of file versions, this action perform the following query for each *File Version*:

1. Gets all related *wasDerivedFrom* file versions (if they exist).
2. Gets the generating activity (if it exists).
3. For the generating activity, gets the list of *wasGeneratedBy* and *used* file versions.

A graph structure of the unique nodes and relationships is returned.

>**Rules:**
- - - - -
+ For file versions that do not exist, no provenance nodes/relations will be returned
+ If a file version does not have a generating activity, then only the file version node is returned.
+ If the user does not have visibilty to a `node` in the resulting graph, the `properties` attribute for that `node` will be a partial resource containing: `kind`, `id`, and `is_deleted`.

>**Properties**
- - - - -
+ **file_versions (object[ ], required)** - The list of file versions (i.e. `dds-file-version`)
+ **file_versions[ ].id (string, required)** - The unique file version id.

**Response messages:**
* 200: This will never happen
* 201: Success
* 401: Unauthorized

+ Request (application/json)

        {
            "file_versions": [
                {
                    "id": "1b80a313-97cf-482d-8d17-9b911bf815b3"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "graph": {
                "nodes": [
                    {
                        "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "labels": ["Activity"],
                        "properties": {
                            "kind": "dds-activity",
                            "id": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                            "name": "RF PI3-Kinase",
                            "is_deleted": false,
                            "audit": { }
                        }
                    },
                    {
                        "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                        "labels": ["File Version"],
                        "properties": {
                            "kind": "dds-file-version",
                            "id": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                            "file": {
                                "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                                "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata"
                            },
                            "version": 1,
                            "label": "Initial raw data from device",
                            "is_deleted": false,
                            "audit": { }
                        }
                    },
                    {
                        "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                        "labels": ["File Version"],
                        "properties": {
                            "kind": "dds-file-version",
                            "id": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                            "file": {
                                "id": "777be35a-98e0-4c2e-9a17-7bc009f9b111",
                                "name": "RSEM_Normalized_PI3K_RNASeq_Matrix.Rdata"
                            },
                            "version": 2,
                            "label": "Alignment performed on raw data",
                            "is_deleted": false,
                            "audit": { }
                        }
                    }
                ],
                "relationships": [
                    {
                        "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
                        "type": "used",
                        "start_node": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "end_node": "89ef1e77-1a0b-40a8-aaca-260d13987f2b",
                        "properties": {
                            "kind": "dds-relation-used",
                            "id": "ac242faf-fba0-4293-a949-0b82ae7ba810",
                            "audit": { }
                        }
                    },
                    {
                        "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
                        "type": "wasGeneratedBy",
                        "start_node": "1b80a313-97cf-482d-8d17-9b911bf815b3",
                        "end_node": "a1ff02a4-b7e9-999d-87x1-66f4c881jka1",
                        "properties": {
                            "kind": "dds-relation-was-generated-by",
                            "id": "372f25e1-01b0-4b8d-9524-e26dd573cc95",
                            "audit": { }
                        }
                    }
                ]
            }
        }
