require 'rails_helper'

RSpec.describe UsedProvRelation, type: :model do
  subject { FactoryGirl.create(:used_prov_relation) }
  let(:resource_serializer) { UsedProvRelationSerializer }
  let(:expected_relationship_type) { 'used' }

  it_behaves_like 'a ProvRelation'

  describe 'validations' do
    it { is_expected.to allow_value('Activity').for(:relatable_from_type) }
    it { is_expected.not_to allow_value('Project').for(:relatable_from_type) }
    it { is_expected.to allow_value('FileVersion').for(:relatable_to_type) }
    it { is_expected.not_to allow_value('Project').for(:relatable_to_type) }

    context 'already generated by activity' do
      let(:used_and_generated_by) { FactoryGirl.create(:activity) }
      let(:used_and_generated) { FactoryGirl.create(:file_version) }
      let(:already_generated) { FactoryGirl.build(:generated_by_activity_prov_relation,
        relatable_to: used_and_generated_by,
        relatable_from: used_and_generated)
      }
      subject { FactoryGirl.build(:used_prov_relation,
        relatable_to: used_and_generated,
        relatable_from: used_and_generated_by)
      }
      it {
        is_expected.to be_valid
        already_generated.save
        is_expected.not_to be_valid
      }
    end
  end
end
