---
http_interactions:
- request:
    method: get
    uri: http://192.168.99.100:12345/auth/v1.0
    body:
      encoding: US-ASCII
      string: ''
    headers:
      X-Auth-User:
      - test:tester
      X-Auth-Key:
      - testing
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Storage-Url:
      - http://192.168.99.100:12345/v1/AUTH_test
      X-Auth-Token:
      - AUTH_tk873232b138f0496680a71aa498ea3103
      Content-Type:
      - text/html; charset=UTF-8
      X-Storage-Token:
      - AUTH_tk873232b138f0496680a71aa498ea3103
      Content-Length:
      - '0'
      X-Trans-Id:
      - txc98322b2996c45e287895-005671bca5
      Date:
      - Wed, 16 Dec 2015 19:33:57 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 16 Dec 2015 19:33:57 GMT
- request:
    method: put
    uri: http://192.168.99.100:12345/v1/AUTH_test/b9291525-7011-4367-87d0-0fea87932008
    body:
      encoding: UTF-8
      string: ''
    headers:
      X-Auth-Token:
      - AUTH_tk873232b138f0496680a71aa498ea3103
      X-Container-Meta-Access-Control-Allow-Origin:
      - "*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Length:
      - '0'
      Content-Type:
      - text/html; charset=UTF-8
      X-Trans-Id:
      - txb8ce7283583a4b9c9bca0-005671bca5
      Date:
      - Wed, 16 Dec 2015 19:33:57 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 16 Dec 2015 19:33:57 GMT
- request:
    method: put
    uri: http://192.168.99.100:12345/v1/AUTH_test/b9291525-7011-4367-87d0-0fea87932008
    body:
      encoding: UTF-8
      string: ''
    headers:
      X-Auth-Token:
      - AUTH_tk873232b138f0496680a71aa498ea3103
      X-Container-Meta-Access-Control-Allow-Origin:
      - "*"
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Content-Length:
      - '76'
      Content-Type:
      - text/html; charset=UTF-8
      X-Trans-Id:
      - tx0465ef9143fc41d69224b-005671bca5
      Date:
      - Wed, 16 Dec 2015 19:33:57 GMT
    body:
      encoding: UTF-8
      string: "<html><h1>Accepted</h1><p>The request is accepted for processing.</p></html>"
    http_version: 
  recorded_at: Wed, 16 Dec 2015 19:33:57 GMT
recorded_with: VCR 3.0.0
